### ISSUE TITLE
problems building due to libmgl make issue

### ISSUE THREAD

**Issue by jl-lewis** [superzerg/logic-analyzer#3]
I know this is probably an issue with libmgl source/build and not with logic-analyzer, but after the lengthy process including building libmgl-dev from source, there was an error during make.

Missing header due to libmgl:
`logic_analyzer.cpp:16:10: fatal error: mgl/mgl_zb.h: No such file or directory
 #include <mgl/mgl_zb.h>`

And the libmgl build issue:
`mgl_fit.cpp:120:24: error: ‘struct gsl_multifit_fdfsolver’ has no member named ‘J’
  gsl_multifit_covar(s->J, 0.0, covar);
                        ^`

Just thought you might have ideas to make this work.
I'm building natively on an RPi3.

**Comment by josharenson** [comment]
I was able to get mgl to compile on my pi w/ `./configure --disable-gsl` but I haven't tried linking logic analyzer against it yet. Have to get to chorin' but will give it a shot later tonight.

EDIT: I get a bunch of linker errors. Will check back if its something easy, else might start looking for alternative software.

**Comment by jspkay** [comment]
I was able to compile and run it. The problem is the version of the gsl library. I installed version 1.16 (which is from about the same year of this repo) from GNU official website.
https://www.gnu.org/software/gsl/#downloading

Last, but not least, I had to remove libmgl-dev with apt, otherwise the linker wasn't able to link everything.

Hope I helped

**Comment by superzerg** [comment]
thanks for the input and glad you made it work!
Unfortunately I do not have access to my pi anymore so I could not really help. I still updated the Readme.
